### ISSUE TITLE
change color scheme of webapp

### ISSUE THREAD

**Issue by stevemar** [IBM/watson-discovery-analyze-data-breaches#9]
joe scheping of the watson discovery team asked if we could change the current purple color to something else (blue?), to differentiate this app from the demo the discovery team created: https://discovery-news-demo.mybluemix.net/

**Comment by rhagarty** [comment]
I modified the large filter area in the middle to dark purple. This way it still works well with all the other light purple/pink components found on the page. Hopefully this simple change is sufficient.
